name: example
description: A flutterwave example project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutterwave_standard:
    path: "../"
  cupertino_icons: ^1.0.2
  uuid: 4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 5.4.3
flutter:

  uses-material-design: true
